export {
  faGlobe,
  faDollarSign,
  faSignIn,
  faX,
  faArrowRight,
  faArrowLeft,
  faUser,
  faCreditCard,
  faClipboardCheck,
  faCheck,
  faHome,
  faEye,
  faChevronRight,
  faRecycle,
  faFileSignature,
  faCircleQuestion,
  faSpinner,
  faPersonWalkingArrowLoopLeft,
  faSearch,
} from '@fortawesome/free-solid-svg-icons';
